classdef DAQ_controller_test < instrumentType

    %% User Configurable Properties
    properties
        % Properties that can be modified by the user
        activeDataChannel      % Currently active data channel
        toggleChannel         % Channel used for toggling data collection
        signalReferenceChannel % Channel used for signal/reference differentiation
        differentiateSignal    % Enable/disable signal/reference differentiation
        takeData
        pollInterval
        samplesToReset %How many samples are needed before the data collection finalizes
        signal
        reference
        referencePoints
        signalPoints
    end

    %% Internal Properties
    properties (SetAccess = {?DAQ_controller ?instrumentType}, GetAccess = public)
        % Properties managed internally by the class
        manufacturer           % DAQ device manufacturer
        analogPortNames        % Available analog port names
        digitalPortNames       % Available digital port names
        counterPortNames       % Available counter port names
        daqName               % Name of the connected DAQ device
        handshake             % DAQ device connection handle
        channelInfo           % Channel configuration information
        dataChannels          % Available data channels
        sampleRate            % Current sample rate
        runningPointValues
        dataType
        procTimer        % timer to pull+process buffer
    end

    %% Creation and Deletion
    methods

        function obj = DAQ_controller_test(configFileName)
            %DAQ_controller Creates a new DAQ controller instance
            %
            %   obj = DAQ_controller(configFileName) creates a new DAQ controller
            %   using the specified configuration file.
            %
            %   Throws:
            %       error - If configFileName is not provided

            if nargin < 1
                error('DAQ_controller:MissingConfig', 'Config file name required as input')
            end

            %Loads config file and checks relevant field names
            configFields = {'channelInfo','manufacturer','identifier','sampleRate'};
            commandFields = {};
            numericalFields = {}; %has units, conversion factor, and min/max
            obj = loadConfig(obj,configFileName,configFields,commandFields,numericalFields);

        end

        function delete(obj)
            disconnect(obj)
        end

        function obj = connect(obj)
            %connect Establishes connection with the DAQ device
            %
            %   connect(obj) connects to the DAQ device and initializes
            %   channels and settings.
            %
            %   Throws:
            %       error - If DAQ is already connected or multiple DAQs detected

            if obj.connected
                error('DAQ_controller:AlreadyConnected', 'DAQ is already connected')
            end

            %Suppresses a warning generated by daq code provided by matlab
            warning('off','MATLAB:subscripting:noSubscriptsSpecified');

            %Checks if config channel labels are valid
            channels = squeeze(struct2cell(obj.channelInfo));
            channels = channels(strcmp(fieldnames(obj.channelInfo),'label'),:);

            obj.dataChannels = find(contains(lower(channels),'data'));
            obj.toggleChannel = find(contains(lower(channels),'toggle')  | contains(lower(channels),'enable'));
            obj.signalReferenceChannel = find(contains(lower(channels),'signal') | contains(lower(channels),'reference'));

            if isempty(obj.dataChannels)
                error('DAQ_controller:MissingDataChannel', 'Config file must contain a channel with a label containing "data"')
            end
            if numel(obj.toggleChannel) ~= 1
                error('DAQ_controller:InvalidToggleChannel', 'Config file must contain exactly 1 channel with a label containing "toggle" or "enable"')
            end
            if numel(obj.signalReferenceChannel) ~= 1
                error('DAQ_controller:InvalidSignalChannel', 'Config file must contain exactly 1 channel with a label containing "signal" or "reference"')
            end

            %Find non-simulated device
            devices = daqlist;
            isSimulated = [devices.DeviceInfo.IsSimulated];
            obj.daqName = devices.DeviceID(~isSimulated);

            if numel(obj.daqName) > 1
                error('DAQ_controller:MultipleDevices', 'Multiple DAQs detected')
            end

            %Store port names
            obj.analogPortNames = devices.DeviceInfo(~isSimulated).Subsystems(1).ChannelNames;
            obj.digitalPortNames = devices.DeviceInfo(~isSimulated).Subsystems(3).ChannelNames;
            obj.counterPortNames = devices.DeviceInfo(~isSimulated).Subsystems(4).ChannelNames;

            %Create DAQ connection
            obj.handshake = daq(obj.manufacturer);
            obj.handshake.Rate = obj.sampleRate;

            %Set default values
            obj.differentiateSignal = true;
            obj.takeData = false;
            obj.pollInterval = .1;
            obj.referencePoints = 0;
            obj.identifier = 'DAQ';

            %Add channels
            for ii = 1:numel(obj.channelInfo)
                addChannel(obj,obj.channelInfo(ii));
            end

            resetDAQ(obj)

            % install a noncapturing callback
            fh = @(src,evt) DAQ_controller_test.storeData(src, evt);
            obj.handshake.ScansAvailableFcn = fh;

            obj.connected = true;
        end

        function disconnect(obj)
            %disconnect Disconnects from the DAQ device
            %
            %   disconnect(obj) disconnects from the DAQ device and cleans up
            %   resources.

            try
                stop(obj.procTimer);
                delete(obj.procTimer);
            catch
            end
            if ~obj.connected
                return;
            end
            try
                DAQ_controller_test.bufferManager("delete");
            catch
            end
            try
                release(obj.handshake); % or proper DAQ cleanup
            catch
            end
            obj.connected = false;
        end
    end

    %% Data Handling
    methods (Static)

        function out = bufferManager(action, dataOrMaxSamples)
            % Simple single-buffer manager (legible, atomic operations)
            % Usage:
            %   bufferManager("init", capacity)        - initialize buffer with capacity (rows)
            %   overwritten = bufferManager("write", MxC)  - append rows MxC to buffer; returns number overwritten
            %   chunk = bufferManager("pop", maxRows)  - remove and return up to maxRows rows (MxC)
            %   n = bufferManager("peek")              - return number of stored rows
            %   bufferManager("delete")                - clear buffer
            %
            % All operations are performed inside a single function call and update
            % persistent state atomically.

            persistent buf head tail count capacity nChannels
            if isempty(buf), buf = []; end

            switch lower(action)
                case "init"
                    if nargin < 2 || ~isscalar(dataOrMaxSamples) || dataOrMaxSamples <= 0
                        error("bufferManager('init',capacity) expects a positive scalar capacity.");
                    end
                    capacity = double(dataOrMaxSamples);
                    nChannels = 0; % unknown until first write
                    buf = zeros(capacity, 1); % allocate rows, channels set on first write
                    head = 1;
                    tail = 1;
                    count = 0;
                    out = [];

                case "write"

                    if isempty(buf)
                        warning("Buffer not initialized. Call bufferManager('init',capacity).");
                        return
                    end
                    if nargin < 2
                        error("bufferManager('write', data) requires data input.");
                    end
                    data = dataOrMaxSamples;
                    [m, c] = size(data);
                    if m == 0
                        out = 0;
                        return
                    end
                    if nChannels == 0
                        % first write sets channel count and allocates storage
                        nChannels = c;
                        buf = zeros(capacity, nChannels);
                    elseif c ~= nChannels
                        error("Channel count changed between writes.");
                    end

                    overwritten = 0;
                    for r = 1:m
                        buf(head, :) = data(r, :);
                        head = head + 1;
                        if head > capacity, head = 1; end
                        if count < capacity
                            count = count + 1;
                        else
                            % buffer full: advance tail (overwrite oldest)
                            tail = tail + 1;
                            if tail > capacity, tail = 1; end
                            overwritten = overwritten + 1;
                        end
                    end
                    out = overwritten;

                case "pop"
                    if isempty(buf)
                        warning("Buffer not initialized. Call bufferManager('init',capacity).");
                        out = [];
                        return
                    end

                    % if nargin < 2 || ~isscalar(dataOrMaxSamples) || dataOrMaxSamples < 0
                    %     error("bufferManager('pop', maxRows) requires nonnegative scalar maxRows.");
                    % end
                    % maxRows = floor(dataOrMaxSamples);
                    if count == 0
                        out = [];
                        return
                    end
                    maxRows = capacity;%mine
                    n = min(maxRows, count);
                    out = zeros(n, nChannels);
                    for k = 1:n
                        out(k, :) = buf(tail, :);
                        tail = tail + 1;
                        if tail > capacity, tail = 1; end
                    end
                    count = count - n;
                    % keep head/tail invariants when empty
                    if count == 0
                        head = tail;
                    end

                case "peek"
                    if isempty(buf)
                        error("Buffer not initialized. Call bufferManager('init',capacity).");
                    end
                    out = count;

                case "delete"
                    buf = [];
                    head = [];
                    tail = [];
                    count = [];
                    capacity = [];
                    nChannels = [];
                    out = [];

                otherwise
                    error("Unknown action.");
            end
        end

        function storeData(handshake,~)
            %storeData Callback function for adding DAQ data to buffer

            if handshake.NumScansAvailable > 0
                data = read(handshake, "all", "OutputFormat", "Matrix");
                nOverwrite = DAQ_controller_test.bufferManager("write",data);
                if nOverwrite > 0
                    warning("Overwrote buffer values. Read buffer more quickly or increase capacity")
                end
            end
        end
    end

    methods

        function startDAQ(obj)
            %startDAQ Resets DAQ counters and data collection
            %
            %   For continuous collection: resets accumulated data
            %   For discrete collection: prepares for new data collection

            if ~obj.connected
                error('DAQ not connected')
            end

            %If the DAQ is continuously gathering data (signal vs reference is
            %enabled AND/OR continuous is hard set)
            if obj.differentiateSignal
                %Set the reference and signal to 0
                resetDAQ(obj)

                %Create buffer if one is not already present
                try
                    DAQ_controller_test.bufferManager("peek");
                catch
                    bufferCapacity = 100 * obj.sampleRate;
                    DAQ_controller_test.bufferManager("init", bufferCapacity);
                end

                if ~isempty(obj.procTimer)
                    stop(obj.procTimer)
                    delete(obj.procTimer)
                    obj.procTimer = [];
                end
                % create processing timer (owned by wrapper) — explicit cleanup needed
                obj.procTimer = timer(...
                    'ExecutionMode','fixedSpacing', ...
                    'Period', obj.pollInterval, ...
                    'TimerFcn', @(~,~) obj.pullAndProcess() ...
                    );
                start(obj.procTimer);
                %Turn on collection
                if ~obj.handshake.Running, start(obj.handshake,"continuous"), end
            else
                if obj.handshake.Running, stop(obj.handshake), end
                resetcounters(obj.handshake)
            end
        end

        function stopDAQ(obj)
            if obj.differentiateSignal
                stop(obj.procTimer);
                stop(obj.handshake);
            end
        end

        function resetDAQ(obj)
            obj.reference = [];
            obj.signal = [];
            obj.referencePoints = [];
            obj.signalPoints = [];
            resetRunningValues(obj)
        end

        function resetRunningValues(obj)
            rpv.ref = 0;
            rpv.sig = 0;
            rpv.nRef = 0;
            rpv.nSig = 0;
            obj.runningPointValues = rpv;
        end

        function pullAndProcess(obj)
            % Pull a bounded chunk from buffer
            raw = DAQ_controller_test.bufferManager("pop");

            if isempty(raw), return; end

            dataOn = logical(raw(:, obj.toggleChannel));
            if nnz(dataOn) == 0
                finalizePoint(obj)%does nothing if running values are 0
                return
            end

            if ~isscalar(obj.samplesToReset)
                error('Samples to reset must be scalar input')
            end

            try
            invData = ~dataOn;
            toggleChanges = diff([0; invData(:); 0]);       % pad to catch edges
            emptyBlockStarts = find(toggleChanges ==  1);%Find where empty blocks start
            dataBlockStarts   = find(toggleChanges == -1);%Find where empty blocks end (data blocks start)

            % keep only blocks with length >= samplesToReset
            blockLength = dataBlockStarts - emptyBlockStarts + 1;
            keep = blockLength >= obj.samplesToReset;
            emptyBlockStarts = emptyBlockStarts(keep);
            dataBlockStarts   = dataBlockStarts(keep);

            %Remove last data block if it "begins" at final value
            %This is due to actually measuring where the empty blocks end
            %rather than where the data blocks start
            if ~isempty(dataBlockStarts) && dataBlockStarts(end) == numel(dataOn)+1
                dataBlockStarts(end) = [];
            end

            %If there are no empty blocks, or if the first empty block does
            %not begin at the start, the first block is a data block
            if isempty(emptyBlockStarts) || emptyBlockStarts(1) ~= 1
                dataBlockStarts(2:end+1) = dataBlockStarts;
                dataBlockStarts(1) = 1;
            end

            %Get list of all blocks
            dataBlockStarts = dataBlockStarts(:);%Ensure vertical concatenation
            emptyBlockStarts = emptyBlockStarts(:);
            allBlocks = sort([dataBlockStarts;emptyBlockStarts]);
            catch ME
                try
                    assignin("base","raw",raw)
                    assignin("base","emptyBlockStarts",emptyBlockStarts)
                    assignin("base","dataBlockStarts",dataBlockStarts)
                catch
                end
                warning('Error in block analysis')
                rethrow(ME)
            end

            %For each block
            for blockNumber = 1:numel(allBlocks)
                if ismember(allBlocks(blockNumber),emptyBlockStarts)
                    %Begins empty block
                    %Finalize point, then move on
                    finalizePoint(obj)
                else
                    %Begins data block
                    %Add data from the start of the data block to the start
                    %of the next empty block, or the end of the run
                    dataBlockStart = dataBlockStarts(dataBlockStarts == allBlocks(blockNumber));
                    if blockNumber ~= numel(allBlocks)
                        dataBlockEnd = allBlocks(blockNumber+1);
                    else
                        dataBlockEnd = numel(dataOn);
                    end

                    processBlock(obj,raw(dataBlockStart:dataBlockEnd,:));
                end
            end


        end

        function finalizePoint(obj)
            %Sets current running values as the next point

            try
            %Don't finalize if there are no points
            if obj.runningPointValues.nRef == 0
                return
            end

            if numel(obj.referencePoints) > 100000
                error('Number of points stored in DAQ exceeds limit')
            end

            if obj.runningPointValues.nRef+obj.runningPointValues.nSig < 100
                warning("Number of reference and signal points lower than 100, discarding data")
                resetRunningValues(obj)
                return
            end

            if isempty(obj.runningPointValues.ref)
                error('No active data channel selected')
            end

            obj.referencePoints(end+1) = obj.runningPointValues.nRef;
            obj.signalPoints(end+1) = obj.runningPointValues.nSig;
            obj.reference(end+1) = obj.runningPointValues.ref;
            obj.signal(end+1) = obj.runningPointValues.sig;
            %For voltage, processing step produces average
            switch obj.dataType
                case 'Counter'
                case 'Voltage'
                    obj.reference(end) = obj.reference(end)/ obj.referencePoints(end);
                    obj.signal(end) = obj.signal(end)/ obj.signalPoints(end);
                case 'Digital'
            end
            resetRunningValues(obj)
            catch ME                
                warning('error in finalizing')
                assignin("base","ME",ME)
                rethrow(ME)                
            end
        end

        function processBlock(obj,raw)
            %***NEED TO ADD COUNTER

            try
            dataOn = logical(raw(:, obj.toggleChannel));

            if ~obj.differentiateSignal
                ref = sum(raw(dataOn, obj.activeDataChannel));
                sig = 0;
            else
                signalOn = raw(:, obj.signalReferenceChannel) ~= 0;
                idxSig = dataOn & signalOn;
                idxRef = dataOn & ~signalOn;
                sig = sum(raw(idxSig, obj.activeDataChannel));
                ref = sum(raw(idxRef, obj.activeDataChannel));
            end

            %Add values to running total
            obj.runningPointValues.ref = obj.runningPointValues.ref+ref;
            obj.runningPointValues.sig = obj.runningPointValues.sig+sig;
            obj.runningPointValues.nRef = obj.runningPointValues.nRef+sum(idxRef);
            obj.runningPointValues.nSig = obj.runningPointValues.nSig+sum(idxSig);
            catch ME
                try
                    assignin("base","raw",raw)
                catch
                end
                warning('error in processing')
                rethrow(ME)
            end
        end

    end

    %% Channel Modification
    methods

        function addChannel(obj,channelInfo)
            %addChannel Adds a channel to the DAQ device
            %
            %   addChannel(obj,channelInfo) adds a channel based on the
            %   provided configuration.
            %
            %   Required fields in channelInfo:
            %       - dataType: 'voltage', 'counter', or 'digital'
            %       - port: Port name for the channel
            %
            %   Throws:
            %       error - If required fields are missing or invalid

            mustContainField(channelInfo,{'dataType','port'})

            %Set data type and valid port names based on input type
            switch lower(channelInfo.dataType)
                case {'v','voltage','analog'}
                    dType = 'Voltage';
                    portNames = 'analogPortNames';
                case {'counter','cntr','count','edge','edge count','edgecount'}
                    dType = 'EdgeCount';
                    portNames = 'counterPortNames';
                case {'digital','binary'}
                    dType = 'Digital';
                    portNames = 'digitalPortNames';
                otherwise
                    error('DAQ_controller:InvalidDataType', ...
                        'Invalid dataType for channel %d. Must be "voltage", "counter", or "digital"',ii)
            end

            if ~any(strcmp(channelInfo.port,obj.(portNames)))
                error('DAQ_controller:InvalidPort', 'Invalid port name. See %s for valid names',portNames)
            end

            %Loads the indicated channel
            addinput(obj.handshake,obj.daqName,channelInfo.port,dType)
            obj.dataType = dType;
            % obj.handshake.UserData.dataType = dataType;
        end

        function idx = getChannelIndex(obj, designation)
            % Returns the index of the channel matching the designation (label or port)
            channels = squeeze(struct2cell(obj.channelInfo));
            labels = channels(strcmp(fieldnames(obj.channelInfo),'label'),:);
            ports = channels(strcmp(fieldnames(obj.channelInfo),'port'),:);
            idx = find(contains(lower(labels),lower(designation)) | contains(lower(ports),lower(designation)));
            if numel(idx) ~= 1
                error('%s is an invalid channel designation. A designation must correspond to exactly 1 channel''s port or label', designation);
            end
        end

        function set.activeDataChannel(obj,val)
            %Sets active data channel number/name based on designation given.
            %Designation can be the channel port or channel label so long as it is unique to that channel
            if ~obj.connected
                obj.presets.activeDataChannel = val;
                return
            end
            obj.activeDataChannel = getChannelIndex(obj, val);        
            %set data type based on active data channel
            obj.dataType = getDataType(obj, obj.activeDataChannel); %#ok<MCSUP>
        end

        function dataType = getDataType(obj, channelNumber)
            % Returns the data type of the specified channel
            switch lower(obj.channelInfo(channelNumber).dataType)
                case {'v','voltage','analog'}
                    dataType = 'Voltage';
                case {'counter','cntr','count','edge','edge count','edgecount'}
                    dataType = 'EdgeCount';
                case {'digital','binary'}
                    dataType = 'Digital';
            end
        end
    end

end



